name: Android Build

on:
  push:
    branches:
      - main
  pull_request:

  workflow_dispatch:

jobs:
  build:
    name: Build APKs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Execute Permission for Gradle
        run: chmod +x gradlew

      - name: Generate Debug APK
        run: ./gradlew assembleDebug

      - name: Generate Test Keystore
        run: |
          keytool -genkeypair -v -keystore testkey.jks -keyalg RSA -keysize 2048 -validity 10000 \
          -storepass android -keypass android -dname "CN=Test, OU=Android, O=Google, L=Mountain View, S=CA, C=US" \
          -alias androiddebugkey

      - name: Create Signing Properties File
        run: |
          echo "storeFile=testkey.jks" >> keystore.properties
          echo "storePassword=android" >> keystore.properties
          echo "keyAlias=androiddebugkey" >> keystore.properties
          echo "keyPassword=android" >> keystore.properties

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
